import '../styles/main.scss';

import { Header } from '@components';
import { netflixSans } from '@utils/fonts';

export const metadata = {
	title: 'Netflix Clone',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: {
	children: React.ReactNode;
}) {
	return (
		<html
			lang='en'
			className={netflixSans.className}
		>
			<body>
				<Header />
				{children}
			</body>
		</html>
	);
}
