import localFont from 'next/font/local';

const netflixSans = localFont({
	src: [
		{
			path: '../../public/fonts/NetflixSans-Regular.woff2',
			weight: '400',
			style: 'normal'
		},
		{
			path: '../../public/fonts/NetflixSans-Medium.woff2',
			weight: '500',
			style: 'normal'
		},
		{
			path: '../../public/fonts/NetflixSans-Light.woff2',
			weight: '300',
			style: 'normal'
		},
		{
			path: '../../public/fonts/NetflixSans-Bold.woff2',
			weight: '700',
			style: 'normal'
		}
	]
});

export const metadata = {
	title: 'Netflix Clone',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: {
	children: React.ReactNode;
}) {
	return (
		<html
			lang='en'
			className={netflixSans.className}
		>
			<body>{children}</body>
		</html>
	);
}
